server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/rainvare/parcial-backend-ms.git
          default-label: main
          force-pull: true
          search-paths: config-data
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka